[package]
name = "slykey"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "6"
enigo = "0.2"
ksni = { version = "0.3", features = ["blocking"] }
rdev = "0.5"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
